module.exports = function(config) {
  config.set({

    basePath: '../',

    frameworks: ["jasmine"],

    files: [
      'http://maps.googleapis.com/maps/api/js?sensor=false',

      // bower:js
      'components/bower_components/angular/angular.js',
      'components/bower_components/angular-animate/angular-animate.js',
      'components/bower_components/angular-mocks/angular-mocks.js',
      'components/bower_components/angular-sanitize/angular-sanitize.js',
      'components/bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'components/bower_components/angular-ui-router/release/angular-ui-router.js',
      'components/bower_components/angular-ui-utils/ui-utils.js',
      'components/bower_components/angular-toastr/dist/angular-toastr.tpls.js',
      'components/bower_components/jquery/dist/jquery.js',
      'components/bower_components/bootstrap/dist/js/bootstrap.js',
      'components/bower_components/d3/d3.js',
      'components/bower_components/moment/moment.js',
      'components/bower_components/ng-file-upload/ng-file-upload.js',
      'components/bower_components/ObjectId.js/src/main/javascript/Objectid.js',
      'components/bower_components/underscore/underscore.js',
      'components/bower_components/lodash/lodash.js',
      'components/bower_components/angular-google-maps/dist/angular-google-maps.js',
      'components/bower_components/angular-hotkeys/build/hotkeys.min.js',
      'components/bower_components/chosen/chosen.jquery.js',
      'components/bower_components/angular-chosen-localytics/chosen.js',
      'components/bower_components/select2/select2.js',
      'components/bower_components/angular-ui-select2/src/select2.js',
      'components/bower_components/ng-Fx/dist/ngFx.js',
      'components/bower_components/angular-loading-bar/build/loading-bar.js',
      'components/bower_components/angular-bootstrap-datetimepicker/src/js/datetimepicker.js',
      'components/bower_components/angular-date-time-input/src/dateTimeInput.js',
      'components/bower_components/angular-smart-table/dist/smart-table.js',
      'components/bower_components/angular-local-storage/dist/angular-local-storage.js',
      'components/bower_components/metisMenu/dist/metisMenu.js',
      'components/bower_components/angular-aside/dist/js/angular-aside.js',
      'components/bower_components/angular-jwt/dist/angular-jwt.js',
      'components/bower_components/plotly.js/dist/plotly.min.js',
      // endbower

      'components/utils/string-utils.js',
      'components/app.js',


      // injector:js
      'components/affiliation/controller/affiliationController.js',
      'components/affiliation/controller/deleteAffiliationController.js',
      'components/analytics/controller/analyticsController.js',
      'components/analytics/controller/skillsMatrixController.js',
      'components/analytics/controller/teamProjectMatrixController.js',
      'components/analytics/directive/pairingsDirective.js',
      'components/analytics/directive/skillsMatrixDirective.js',
      'components/analytics/directive/teamProjectMatrixDirective.js',
      'components/analytics/service/matrixDataService.js',
      'components/analytics/service/matrixService.js',
      'components/commLog/controller/followupController.js',
      'components/commLog/controller/noteController.js',
      'components/commLog/service/commLogService.js',
      'components/commLog/service/noteService.js',
      'components/common/directive/autoFocus.js',
      'components/common/directive/dateTimeValidation.js',
      'components/common/directive/documentTypeIconDirective.js',
      'components/common/directive/inspinia.js',
      'components/common/filter/capitalise.js',
      'components/common/filter/returnDirtyItems.js',
      'components/common/filter/spaceCapitals.js',
      'components/common/service/alertService.js',
      'components/common/service/dateValidationService.js',
      'components/common/service/docxService.js',
      'components/common/service/eventLogService.js',
      'components/common/service/googleLocationService.js',
      'components/common/service/htmlifyDataService.js',
      'components/common/service/sliderService.js',
      'components/common/service/stackTraceService.js',
      'components/common/service/tabService.js',
      'components/common/service/typeAheadService.js',
      'components/common/service/underscoreService.js',
      'components/index/controller/indexController.js',
      'components/index/controller/jobSummaryController.js',
      'components/index/controller/personnelSummaryController.js',
      'components/index/directive/appVersionDirective.js',
      'components/index/service/indexService.js',
      'components/index/service/searchService.js',
      'components/jobDescription/controller/deleteJobDescriptionController.js',
      'components/jobDescription/controller/jobDescriptionController.js',
      'components/jobDescription/controller/jobDescriptionDocumentationController.js',
      'components/jobDescription/controller/jobDescriptionMissingMandatoryController.js',
      'components/jobDescription/service/jobDescriptionService.js',
      'components/login/controller/loginController.js',
      'components/login/controller/registrationController.js',
      'components/login/directive/passwordsMatchDirective.js',
      'components/login/service/userService.js',
      'components/manageWorkflow/controller/manageWorkflowController.js',
      'components/manageWorkflow/controller/workflowPersonnelController.js',
      'components/manageWorkflow/service/manageWorkflowService.js',
      'components/personnel/controller/deleteFileController.js',
      'components/personnel/controller/deletePersonnelController.js',
      'components/personnel/controller/dirtyPersonnelController.js',
      'components/personnel/controller/personnelContactController.js',
      'components/personnel/controller/personnelController.js',
      'components/personnel/controller/personnelDocumentationController.js',
      'components/personnel/controller/personnelNotesController.js',
      'components/personnel/controller/personnelQualificationController.js',
      'components/personnel/controller/personnelRoleController.js',
      'components/personnel/service/emailService.js',
      'components/personnel/service/fileService.js',
      'components/personnel/service/followupService.js',
      'components/personnel/service/personnelService.js',
      'components/qualification/controller/deleteQualificationController.js',
      'components/qualification/controller/qualificationController.js',
      'components/qualificationReport/controller/qualificationReportController.js',
      'components/qualificationReport/controller/reportOptionsController.js',
      'components/resourceController.js',
      'components/role/controller/deleteRoleController.js',
      'components/role/controller/roleController.js',
      'components/role/service/roleService.js',
      'components/training/controller/deleteTrainingController.js',
      'components/training/controller/trainingController.js',
      'components/utils/string-utils.js',
      'components/web/js/inspinia.js',
      'components/workflow/controller/epc/availableController.js',
      'components/workflow/controller/epc/consideredController.js',
      'components/workflow/controller/epc/formatcvController.js',
      'components/workflow/controller/epc/hiredController.js',
      'components/workflow/controller/epc/interviewController.js',
      'components/workflow/controller/epc/interviewRequestController.js',
      'components/workflow/controller/epc/preEmploymentController.js',
      'components/workflow/controller/epc/qualityController.js',
      'components/workflow/controller/epc/submissionController.js',
      'components/workflow/controller/workflowController.js',
      'components/workflow/controller/workflowProgressController.js',
      'components/workflow/service/workflowService.js',
      'node_modules/jasmine-collection-matchers/lib/pack.js',
      // endinjector

      // injector:testJs
      'components/analytics/test/unit/matrixDataServiceSpec.js',
      'components/analytics/test/unit/matrixServiceSpec.js',
      'components/analytics/test/unit/teamProjectMatrixCtrlSpec.js',
      'components/commLog/test/unit/followupCtrlSpec.js',
      'components/commLog/test/unit/noteCtrlSpec.js',
      'components/common/test/unit/doctypeSpec.js',
      'components/common/test/unit/docxServiceSpec.js',
      'components/common/test/unit/googleLocationServiceSpec.js',
      'components/common/test/unit/tabServiceSpec.js',
      'components/index/test/unit/indexCtrlSpec.js',
      'components/index/test/unit/searchServiceSpec.js',
      'components/jobDescription/test/unit/jobDescriptionCtrlSpec.js',
      'components/jobDescription/test/unit/jobDescriptionServiceSpec.js',
      'components/manageWorkflow/test/unit/manageWorkflowCtrlSpec.js',
      'components/manageWorkflow/test/unit/manageWorkflowServiceSpec.js',
      'components/personnel/test/unit/followupServiceSpec.js',
      'components/personnel/test/unit/personnelCtrlSpec.js',
      'components/personnel/test/unit/personnelNotesCtrlSpec.js',
      'components/personnel/test/unit/personnelRoleCtrlSpec.js',
      'components/personnel/test/unit/personnelServiceSpec.js',
      'components/role/test/unit/roleCtrlSpec.js',
      'components/role/test/unit/roleServiceSpec.js',
      'components/workflow/test/unit/workflowServiceSpec.js',
      // endinjector
    ],

    preprocessors: {
      'components/*/controller/*.js': 'coverage',
      'components/*/service/*.js': 'coverage',
      'components/*/directive/*.js': 'coverage'
    },

    coverageReporter: {
      type: 'cobertura',
      dir: 'coverage/',
      file: 'controller-cobertura.xml'
    },

    logLevel: config.LOG_INFO,

    autoWatch: false,

    singleRun: true,

    reporters: ['progress', 'junit', 'coverage'],

    junitReporter: {
      outputFile: 'report/unit.xml',
      suite: 'unit'
    }

  });
};
