'use strict';

describe('MatrixService', function() {

  var matrixService;

  beforeEach(module('resource'));
  beforeEach(inject(function(MatrixService) {
    matrixService = MatrixService;
  }));

  afterEach(function() {
  });
});

var projectsx = [
  // 0
  {"id":"551aaaa62f7c3123030014e0","name":"Okhafort","personnel":[{"id":"551aaa9bd4c6c29780d621b8","name":"Sonmarc Tonnessmarc","occupation":"Railway Electrician","roles":[{"_id":"551aaa9bd4c6c29780d621af","roleName":"Chemical Engineer","client":"Woodside","projects":[{"id":"Okhafort","text":"Okhafort","location":"Sydney","projectExperience":["eeha"],"phaseExperience":["opsmaint"]},{"id":"Lintin","text":"Lintin","location":"Perth","projectExperience":["eeha"],"phaseExperience":["commissioning"]},{"id":"Estin","text":"Estin","location":"Perth","projectExperience":["other"],"phaseExperience":["construction"]}]}]}],"projectExperience":"eeha","colour":"#1f77b4","ycoords":[{"y":16,"x":160}]},
  // 1
  {"id":"551aaaa62f7c3123030014e1","name":"Lintin","personnel":[{"id":"551aaa9bd4c6c29780d621b8","name":"Sonmarc Tonnessmarc","occupation":"Railway Electrician","roles":[{"_id":"551aaa9bd4c6c29780d621af","roleName":"Chemical Engineer","client":"Woodside","projects":[{"id":"Okhafort","text":"Okhafort","location":"Sydney","projectExperience":["eeha"],"phaseExperience":["opsmaint"]},{"id":"Lintin","text":"Lintin","location":"Perth","projectExperience":["eeha"],"phaseExperience":["commissioning"]},{"id":"Estin","text":"Estin","location":"Perth","projectExperience":["other"],"phaseExperience":["construction"]}]}]}],"projectExperience":"eeha","colour":"#aec7e8","ycoords":[{"y":16,"x":128}]},
  // 2
  {"id":"551aaaa62f7c3123030014e3","name":"Sitees","personnel":[{"id":"551aaa9bd4c6c29780d621c3","name":"Bertton Jeffjeffand","occupation":"Chemist","roles":[{"_id":"551aaa9bd4c6c29780d621b9","roleName":"Bogger Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Sitees","text":"Sitees","location":"Sydney","projectExperience":["rpn"],"phaseExperience":["decommissioning"]},{"id":"Tinrould","text":"Tinrould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Okhatin","text":"Okhatin","location":"Mt Isa","projectExperience":["rpn"],"phaseExperience":["engineering"]}]},{"_id":"551aaa9bd4c6c29780d621ba","roleName":"Jumbo Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Fortrould","text":"Fortrould","location":"Perth","projectExperience":["rpn"],"phaseExperience":["construction"]},{"id":"Siteokha","text":"Siteokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]},{"id":"Lingold","text":"Lingold","location":"Northwest Shelf","projectExperience":["onOG"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"rpn","colour":"#ffbb78","ycoords":[{"y":0,"x":16}]},
  // 3
  {"id":"551aaaa62f7c3123030014e5","name":"Okhatin","personnel":[{"id":"551aaa9bd4c6c29780d621c3","name":"Bertton Jeffjeffand","occupation":"Chemist","roles":[{"_id":"551aaa9bd4c6c29780d621b9","roleName":"Bogger Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Sitees","text":"Sitees","location":"Sydney","projectExperience":["rpn"],"phaseExperience":["decommissioning"]},{"id":"Tinrould","text":"Tinrould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Okhatin","text":"Okhatin","location":"Mt Isa","projectExperience":["rpn"],"phaseExperience":["engineering"]}]},{"_id":"551aaa9bd4c6c29780d621ba","roleName":"Jumbo Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Fortrould","text":"Fortrould","location":"Perth","projectExperience":["rpn"],"phaseExperience":["construction"]},{"id":"Siteokha","text":"Siteokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]},{"id":"Lingold","text":"Lingold","location":"Northwest Shelf","projectExperience":["onOG"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"rpn","colour":"#98df8a","ycoords":[{"y":0,"x":48}]},
  // 4
  {"id":"551aaaa62f7c3123030014e6","name":"Fortrould","personnel":[{"id":"551aaa9bd4c6c29780d621c3","name":"Bertton Jeffjeffand","occupation":"Chemist","roles":[{"_id":"551aaa9bd4c6c29780d621b9","roleName":"Bogger Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Sitees","text":"Sitees","location":"Sydney","projectExperience":["rpn"],"phaseExperience":["decommissioning"]},{"id":"Tinrould","text":"Tinrould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Okhatin","text":"Okhatin","location":"Mt Isa","projectExperience":["rpn"],"phaseExperience":["engineering"]}]},{"_id":"551aaa9bd4c6c29780d621ba","roleName":"Jumbo Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Fortrould","text":"Fortrould","location":"Perth","projectExperience":["rpn"],"phaseExperience":["construction"]},{"id":"Siteokha","text":"Siteokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]},{"id":"Lingold","text":"Lingold","location":"Northwest Shelf","projectExperience":["onOG"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"rpn","colour":"#d62728","ycoords":[{"y":0,"x":80}]},
  // 5
  {"id":"551aaaa62f7c3123030014e7","name":"Siteokha","personnel":[{"id":"551aaa9bd4c6c29780d621c3","name":"Bertton Jeffjeffand","occupation":"Chemist","roles":[{"_id":"551aaa9bd4c6c29780d621b9","roleName":"Bogger Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Sitees","text":"Sitees","location":"Sydney","projectExperience":["rpn"],"phaseExperience":["decommissioning"]},{"id":"Tinrould","text":"Tinrould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Okhatin","text":"Okhatin","location":"Mt Isa","projectExperience":["rpn"],"phaseExperience":["engineering"]}]},{"_id":"551aaa9bd4c6c29780d621ba","roleName":"Jumbo Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Fortrould","text":"Fortrould","location":"Perth","projectExperience":["rpn"],"phaseExperience":["construction"]},{"id":"Siteokha","text":"Siteokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]},{"id":"Lingold","text":"Lingold","location":"Northwest Shelf","projectExperience":["onOG"],"phaseExperience":["decommissioning"]}]}]},{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"fpso","colour":"#ff9896","ycoords":[{"y":0,"x":0},{"y":32,"x":0}]},
  // 6
  {"id":"551aaaa62f7c3123030014e8","name":"Lingold","personnel":[{"id":"551aaa9bd4c6c29780d621c3","name":"Bertton Jeffjeffand","occupation":"Chemist","roles":[{"_id":"551aaa9bd4c6c29780d621b9","roleName":"Bogger Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Sitees","text":"Sitees","location":"Sydney","projectExperience":["rpn"],"phaseExperience":["decommissioning"]},{"id":"Tinrould","text":"Tinrould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Okhatin","text":"Okhatin","location":"Mt Isa","projectExperience":["rpn"],"phaseExperience":["engineering"]}]},{"_id":"551aaa9bd4c6c29780d621ba","roleName":"Jumbo Operator","client":"Gold Holdings Pty Ltd","projects":[{"id":"Fortrould","text":"Fortrould","location":"Perth","projectExperience":["rpn"],"phaseExperience":["construction"]},{"id":"Siteokha","text":"Siteokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]},{"id":"Lingold","text":"Lingold","location":"Northwest Shelf","projectExperience":["onOG"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"onOG","colour":"#9467bd","ycoords":[{"y":0,"x":64}]},
  // 7
  {"id":"551aaaa62f7c3123030014e9","name":"Fortgold","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"onOG","colour":"#c5b0d5","ycoords":[{"y":32,"x":112}]},
  // 8
  {"id":"551aaaa62f7c3123030014ea","name":"Rouldfrank","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"fpso","colour":"#8c564b","ycoords":[{"y":32,"x":208}]},
  // 9
  {"id":"551aaaa62f7c3123030014eb","name":"Quefort","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"lng","colour":"#c49c94","ycoords":[{"y":32,"x":176}]},
  // 10
  {"id":"551aaaa62f7c3123030014ec","name":"Minelin","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"fpso","colour":"#e377c2","ycoords":[{"y":32,"x":144}]},
  // 11
  {"id":"551aaaa62f7c3123030014ed","name":"Queque","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"fpso","colour":"#f7b6d2","ycoords":[{"y":32,"x":192}]},
  // 12
  {"id":"551aaaa62f7c3123030014ee","name":"Sitees","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"eeha","colour":"#7f7f7f","ycoords":[{"y":32,"x":32}]},
  // 13
  {"id":"551aaaa62f7c3123030014f0","name":"Esokha","personnel":[{"id":"551aaa9bd4c6c29780d621cb","name":"Bertshire Nesssonwick","occupation":"Worker","roles":[{"_id":"551aaa9bd4c6c29780d621c4","roleName":"Mine Geologist","client":"Rio Tinto","projects":[{"id":"Fortgold","text":"Fortgold","location":"Perth","projectExperience":["onOG"],"phaseExperience":["construction"]},{"id":"Rouldfrank","text":"Rouldfrank","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]},{"id":"Quefort","text":"Quefort","location":"Perth","projectExperience":["lng"],"phaseExperience":["construction"]}]},{"_id":"551aaa9bd4c6c29780d621c5","roleName":"Jumbo Operator","client":"Woodside","projects":[{"id":"Minelin","text":"Minelin","location":"Sydney","projectExperience":["fpso"],"phaseExperience":["procurement"]},{"id":"Queque","text":"Queque","location":"Perth","projectExperience":["fpso"],"phaseExperience":["installation"]},{"id":"Siteokha","text":"Siteokha","location":"Perth","projectExperience":["fpso"],"phaseExperience":["commissioning"]}]},{"_id":"551aaa9bd4c6c29780d621c6","roleName":"Geophysicist","client":"BHP","projects":[{"id":"Sitees","text":"Sitees","location":"Mt Isa","projectExperience":["eeha"],"phaseExperience":["construction"]},{"id":"Querould","text":"Querould","location":"Northwest Shelf","projectExperience":["other"],"phaseExperience":["engineering"]},{"id":"Esokha","text":"Esokha","location":"Mt Isa","projectExperience":["fpso"],"phaseExperience":["decommissioning"]}]}]}],"projectExperience":"fpso","colour":"#bcbd22","ycoords":[{"y":32,"x":96}]}
];

var orders = {
  personnel: [],
  project: [1, 0, 12, 13, 10, 11, 8, 5, 9, 7, 6, 4, 3, 2, 14]
}